### ISSUE TITLE
Not able to perform Gradle Project Sync

### ISSUE THREAD

**Issue by BillyYiuCimda** [millerGrey/BLE-android-example#1]
Unable to find method ''void org.gradle.api.internal.DefaultDomainObjectSet.<init>(java.lang.Class)''
'void org.gradle.api.internal.DefaultDomainObjectSet.<init>(java.lang.Class)'

Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)

Re-download dependencies and sync project (requires network)
The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.

Stop Gradle build processes (requires restart)
Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

**Comment by millerGrey** [comment]
I updated versions of gradle. Try to sync and build now.

**Comment by BillyYiuCimda** [comment]
It is OK now, thanks.
